[pytest]
pythonpath = .
python_files = tests.py test_*.py
python_classes = Test* *Test* *Test *Tests
addopts = -m "not live"
env =
  ENV=test
markers =
  live: marks tests that sends requests to external services e.g. vinted
