"""empty message

Revision ID: b71503b49197
Revises: 19d90bc147d7
Create Date: 2025-12-26 12:37:21.989033

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b71503b49197"
down_revision: str | None = "19d90bc147d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shs_users", sa.Column("username", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("shs_users", "username")
    # ### end Alembic commands ###
