"""empty message

Revision ID: 19d90bc147d7
Revises:
Create Date: 2025-12-23 15:34:54.462315

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19d90bc147d7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shs_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("vinted_url", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vinted_url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shs_users")
    # ### end Alembic commands ###
