events {}
http {
    include       mime.types;
    server {
        listen 443 ssl;
        server_name your-domain.pl www.your-domain.pl;
        ssl_certificate     /etc/letsencrypt/live/your-domain.pl/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/your-domain.pl/privkey.pem;

        location / {
            proxy_pass http://shs-backend:8000;
        }
    }
    server {
        listen 80;
        server_name your-domain.pl www.your-domain.pl;
        return 301 https://your-domain.pl$request_uri;
    }
}
