events {}
http {
    include       mime.types;
    server {
        listen 443 ssl;
        server_name secondswagstore.pl www.secondswagstore.pl;
        ssl_certificate     /etc/letsencrypt/live/secondswagstore.pl/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/secondswagstore.pl/privkey.pem;

        location / {
            proxy_pass http://shs-backend:8000;
        }
    }
    server {
        listen 80;
        server_name secondswagstore.pl www.secondswagstore.pl;
        return 301 https://secondswagstore.pl$request_uri;
    }
}
