services:
  db:
    image: postgres:17
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 2s
    env_file: ../src/env/.env.production
    networks:
      - db_network
    volumes:
      - dbdata:/var/lib/postgresql/data
  migrations:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    command: sh -c 'cd src/infrastructure/sqlalchemy && alembic upgrade head'
    env_file: ../src/env/.env.production
    networks:
      - db_network
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    env_file: ../src/env/.env.production
    networks:
      - db_network
      - backend_network
    healthcheck:
      test: python -c 'import urllib.request; urllib.request.urlopen("http://backend:8000/api/health")'
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 2s
    depends_on:
      migrations:
        condition: service_completed_successfully
  api-gateway:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend_network
    volumes:
      - ../api_gateway/nginx_production.conf:/etc/nginx/nginx.conf:ro
      - certbot_volume:/etc/letsencrypt
    depends_on:
      backend:
        condition: service_healthy
  certbot:
    image: certbot/certbot
    container_name: certbot
    profiles:
      - certbot
    restart: "no"
    ports:
      - "80:80"
    volumes:
      - certbot_volume:/etc/letsencrypt
    command: certonly --standalone --email bartektrybalaa@gmail.com --agree-tos --preferred-challenges http -d your-domain.pl
volumes:
  dbdata:
    driver: local
  certbot_volume:
    driver: local
networks:
  db_network:
    driver: bridge
  backend_network:
    driver: bridge
